apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sak
  template:
    metadata:
      labels:
        app: sak
    spec:
      containers:
      - name: python-webapp
        image: python-webapp:latest  
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-webapp-service
spec:
  selector:
    app: sak
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30090
  type: NodePort  
